apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummy-cluster-network-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummy-cluster-network-controller
rules:
- apiGroups: [ "network.harvester.io" ]
  resources: [ "dummyclusternetworks", "dummyclusternetworks/status" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups: [ "k8s.cni.cncf.io" ]
  resources: [ "network-attachment-definitions" ]
  verbs: [ "get", "list", "create", "update", "delete", "watch" ]
- apiGroups: [ "apps" ]
  resources: [ "daemonsets" ]
  verbs: [ "get", "list", "create", "update", "delete", "watch" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "kubevirt.io" ]
  resources: [ "virtualmachines", "virtualmachineinstances" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummy-cluster-network-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dummy-cluster-network-controller
subjects:
- kind: ServiceAccount
  name: dummy-cluster-network-controller
  namespace: kube-system