apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummyclusternetworks.network.harvester.io
spec:
  group: network.harvester.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                bridgeName:
                  type: string
                nadName:
                  type: string
                nadNamespace:
                  type: string
              required: ["bridgeName","nadName","nadNamespace"]
            status:
              type: object
              properties:
                phase:
                  type: string
                reason:
                  type: string
      subresources:
        status: {}
  scope: Cluster
  names:
    plural: dummyclusternetworks
    singular: dummyclusternetwork
    kind: DummyClusterNetwork
    shortNames:
      - dcn